version: '2'

services:
   mqttsn-gateway:
     build: ./mqttsn-gateway
     ports:
       - 10000:10000
# Put it on the host network until we work out custom network configurations
     network_mode: host
